# -*- coding: utf-8 -*-
"""Arquivo Inicial - Minicurso Analise de Dados Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMhDOR5M73oFvSTzN4xCt7Su8-D5Uioj

# Desafio:

Você trabalha em uma grande empresa de Cartão de Crédito e o diretor da empresa percebeu que o número de clientes que cancelam seus cartões tem aumentado significativamente, causando prejuízos enormes para a empresa

O que fazer para evitar isso? Como saber as pessoas que têm maior tendência a cancelar o cartão?

# O que temos:

Temos 1 base de dados com informações dos clientes, tanto clientes atuais quanto clientes que cancelaram o cartão

Download da Base de Dados: Botão na página

Referência: https://www.kaggle.com/sakshigoyal7/credit-card-customers
"""

from google.colab import drive
drive.mount('/content/drive')

"""- Passo 1: Imprtar a base de dados
- Passo 2: Visualizar e tratar essa base de dados
- Passo 3: "Dar uma olhada" na sua base de dados (olhar as colunas e as informações para assim já ter um panorama geral das informações disponíveis para resolver o desafio)
- Passo 4: Construir uma análise para identificar o motivo de cancelamento
- Obejtivo da análise: qual o motivo ou os principais motivos dos clientes estarem cancelando o cartão de crédito

"""

import pandas as pd

tabela = pd.read_csv("/content/drive/MyDrive/Minicurso Análise de dados com Python - Hashtag Treinamentos/ClientesBanco.csv", encoding="latin1")
tabela = tabela.drop("CLIENTNUM", axis=1)
display (tabela)

"""# **Agora vamos tratar valores vazios e exibir um resumo das colunas da base de dados**"""

tabela = tabela.dropna()
display(tabela.info())

display(tabela.describe().round(2))

"""# **Vamos avaliar como está a divisão entre Cliente x Cancelados**

"""

qtde_categoria = tabela["Categoria"].value_counts()
display(qtde_categoria)

qtde_categoria_perc = tabela["Categoria"].value_counts(normalize=True)
display(qtde_categoria_perc)

"""# **Temos várias formas de descobrir o motivo do cancelamento**
  - Podemos olhar a comparação entre Clientes e Cancelados em cada uma das colunas da nossa base de dados, para ver se essa informação traz algum insight novo
"""

import plotly.express as px

for coluna in tabela:
  grafico = px.histogram(tabela, x=coluna, color="Categoria")
  grafico.show()

"""# **Informações retiradas da análise**

- Me parece que quanto mais produtos contratados um cliente tem, menor a chance dele cancelar
- E quanto mais transações e quanto maior o valor de transação, menor a chance dele cancelar
- Quanto maior a quantidade de contatos que a pessoa teve que fazer, maior a chance dela cancelar

"""